ALTER SESSION SET CONTAINER = XEPDB1;

// 1
CREATE TABLESPACE TS_ZAI
    DATAFILE 'TS_ZAI.dbf'
    SIZE 7 m
    AUTOEXTEND ON NEXT 5 m
    MAXSIZE 20 m
    EXTENT MANAGEMENT LOCAL;
    
DROP TABLESPACE TS_ZAI INCLUDING CONTENTS AND DATAFILES;


// 2
CREATE TEMPORARY TABLESPACE TS_ZAI_TEMP
    TEMPFILE 'TS_ZAI_TEMP.dbf'
    SIZE 5 m
    AUTOEXTEND ON NEXT 3 m
    MAXSIZE 30 m
    EXTENT MANAGEMENT LOCAL;
    
DROP TABLESPACE TS_ZAI_TEMP INCLUDING CONTENTS AND DATAFILES;


// 3
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES
FROM DBA_DATA_FILES
UNION
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES
FROM DBA_TEMP_FILES;


// 4
CREATE ROLE RL_ZAICORE;
GRANT CREATE SESSION,
        CREATE TABLE,
        CREATE TABLESPACE,
        CREATE VIEW,
        CREATE PROCEDURE,
        DROP ANY TABLE,
        DROP TABLESPACE,
        DROP ANY VIEW,
        DROP ANY PROCEDURE TO RL_ZAICORE;
        
DROP ROLE RL_ZAICORE;


// 5
SELECT * FROM DBA_ROLES WHERE ROLE LIKE 'RL%';
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_ZAICORE';


// 6
CREATE PROFILE PF_ZAICORE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

DROP PROFILE PF_ZAICORE CASCADE;


// 7 
SELECT * FROM DBA_PROFILES;
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_ZAICORE';
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';


// 8
CREATE USER ZAICORE IDENTIFIED BY 12345
    DEFAULT TABLESPACE TS_ZAI QUOTA UNLIMITED ON TS_ZAI
    TEMPORARY TABLESPACE TS_ZAI_TEMP
    PROFILE PF_ZAICORE
    ACCOUNT UNLOCK
    PASSWORD EXPIRE;

GRANT RL_ZAICORE TO ZAICORE;

REVOKE RL_ZAICORE FROM ZAICORE;

DROP USER ZAICORE;


// 9

// docker exec -it oracle-xe bash
// sqlplus sys/MyStrongPassw0rd@XE as sysdba
// ALTER SESSION SET CONTAINER = XEPDB1;
// ALTER USER ZAICORE IDENTIFIED BY NewPassword123;

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CONTAINER = CDB$ROOT;

SELECT CON_ID, USERNAME, PROFILE
FROM CDB_USERS
WHERE PROFILE = 'PF_ZAICORE'
ORDER BY CON_ID, USERNAME;


// 10
CREATE TABLE ZAI_TABLE (
    ID   NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    CREATED_AT DATE DEFAULT SYSDATE
);

INSERT INTO ZAI_TABLE (ID, NAME) VALUES (1, 'Первая запись');
INSERT INTO ZAI_TABLE (ID, NAME) VALUES (2, 'Вторая запись');

DROP TABLE ZAI_TABLE;

COMMIT;

CREATE VIEW ZAI_VIEW AS
    SELECT ID, NAME
    FROM ZAI_TABLE
    WHERE ID > 0;

DROP VIEW ZAI_VIEW;


// 11
CREATE TABLESPACE ZAI_QDATA
    DATAFILE 'ZAI_QDATA.dbf' 
    SIZE 10M
    OFFLINE;

ALTER DATABASE DATAFILE 'ZAI_QDATA.dbf' ONLINE;
ALTER TABLESPACE ZAI_QDATA ONLINE;

DROP TABLESPACE ZAI_QDATA INCLUDING CONTENTS AND DATAFILES;

CREATE USER ZAI IDENTIFIED BY 12345
    DEFAULT TABLESPACE ZAI_QDATA QUOTA 2M ON ZAI_QDATA
    PROFILE PF_ZAICORE
    ACCOUNT UNLOCK;

GRANT RL_ZAICORE TO ZAI;

DROP USER ZAI;

CREATE TABLE ZAI.ZAI_T1 (
    ID NUMBER PRIMARY KEY,
    DESCR VARCHAR2(100)
) TABLESPACE ZAI_QDATA;

SELECT OWNER, TABLE_NAME, TABLESPACE_NAME
FROM DBA_TABLES
WHERE TABLE_NAME = 'ZAI_T1';

INSERT INTO ZAI.ZAI_T1 VALUES (1, 'Один');
INSERT INTO ZAI.ZAI_T1 VALUES (2, 'Два');
INSERT INTO ZAI.ZAI_T1 VALUES (3, 'Три');

DROP TABLE ZAI.ZAI_T1;

COMMIT;
