CREATE PLUGGABLE DATABASE SPORTICS
    ADMIN USER ADMINISTRATOR IDENTIFIED BY 12345
    ROLES = (DBA)
    FILE_NAME_CONVERT = ('/opt/oracle/oradata/XE/',
                        '/opt/oracle/oradata/XE/SPORTICS/');

ALTER PLUGGABLE DATABASE SPORTICS OPEN;
ALTER SESSION SET CONTAINER = SPORTICS;

ALTER PLUGGABLE DATABASE SPORTICS CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE SPORTICS INCLUDING DATAFILES;

GRANT EXECUTE ON DBMS_CRYPTO TO ADMINISTRATOR WITH GRANT OPTION;
GRANT EXECUTE ON DBMS_JSON TO ADMINISTRATOR;


CREATE TABLESPACE SPORTICS_TS
    DATAFILE 'SPORTICS_TS.dbf'
    SIZE 200M
    AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;
    
ALTER USER ADMINISTRATOR QUOTA UNLIMITED ON SPORTICS_TS;
    
DROP TABLESPACE SPORTICS_TS INCLUDING CONTENTS AND DATAFILES;


-- 1. Таблица учётных записей всех пользователей
CREATE TABLE USERS (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(50) NOT NULL,
    password_hash  VARCHAR2(200) NOT NULL,
    password_salt  RAW(16) NOT NULL,
    role_name      VARCHAR2(20) NOT NULL CHECK (role_name IN ('ROLE_ADMIN', 'ROLE_TRAINER', 'ROLE_CLIENT')),
    created_at     DATE DEFAULT SYSDATE,
    is_active      CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y','N')),
    must_change_password CHAR(1) DEFAULT 'N' CHECK (must_change_password IN ('Y','N'))
) TABLESPACE sportics_ts;


CREATE UNIQUE INDEX idx_users_username
    ON USERS(username);

CREATE INDEX idx_users_role_name
    ON USERS(role_name);

CREATE INDEX idx_users_is_active
    ON USERS(is_active);

CREATE INDEX idx_users_must_change_password
    ON USERS(must_change_password);

CREATE INDEX idx_users_created_at
    ON USERS(created_at);

DROP INDEX idx_users_username;
DROP INDEX idx_users_role_name;
DROP INDEX idx_users_is_active;
DROP INDEX idx_users_must_change_password;
DROP INDEX idx_users_created_at;


-- 2. Таблица клиентов клуба
CREATE TABLE CLIENTS (
    client_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER UNIQUE,
    first_name        VARCHAR2(50) NOT NULL,
    last_name         VARCHAR2(50) NOT NULL,
    phone_number      VARCHAR2(20),
    email             VARCHAR2(100) UNIQUE,
    date_of_birth     DATE,
    registration_date DATE DEFAULT SYSDATE,
    status            VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
    CONSTRAINT fk_clients_user FOREIGN KEY (user_id)
        REFERENCES USERS(user_id) ON DELETE CASCADE
) TABLESPACE sportics_ts;


-- 3. Таблица тренеров
CREATE TABLE COACHES (
    coach_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER UNIQUE,
    first_name    VARCHAR2(50) NOT NULL,
    last_name     VARCHAR2(50) NOT NULL,
    phone_number  VARCHAR2(20),
    email         VARCHAR2(100) UNIQUE,
    specialization VARCHAR2(100),
    hire_date     DATE DEFAULT SYSDATE,
    status        VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
    CONSTRAINT fk_coaches_user FOREIGN KEY (user_id)
        REFERENCES USERS(user_id) ON DELETE CASCADE
) TABLESPACE sportics_ts;


-- 4. Таблица типов абонементов
CREATE TABLE MEMBERSHIPS (
    membership_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(50) NOT NULL,
    description     VARCHAR2(200),
    duration_months NUMBER(2) CHECK (duration_months > 0),
    price           NUMBER(10,2) CHECK (price >= 0)
) TABLESPACE sportics_ts;


-- 5. Таблица заказов на абонементы
CREATE TABLE MEMBERSHIP_ORDERS (
    order_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id      NUMBER NOT NULL,
    membership_id  NUMBER NOT NULL,
    order_date     DATE DEFAULT SYSDATE,
    start_date     DATE,
    end_date       DATE,
    status         VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','EXPIRED','CANCELLED')),
    CONSTRAINT fk_order_client FOREIGN KEY (client_id)
        REFERENCES CLIENTS (client_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_membership FOREIGN KEY (membership_id)
        REFERENCES MEMBERSHIPS (membership_id) ON DELETE CASCADE
) TABLESPACE sportics_ts;


-- 6. Таблица расписания тренировок
CREATE TABLE SCHEDULES (
    schedule_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coach_id      NUMBER,
    session_name  VARCHAR2(100) NOT NULL,
    session_date  DATE NOT NULL,
    start_time    TIMESTAMP NOT NULL,
    end_time      TIMESTAMP NOT NULL,
    capacity      NUMBER(3) DEFAULT 10 CHECK (capacity > 0),
    CONSTRAINT fk_schedule_coach FOREIGN KEY (coach_id)
        REFERENCES COACHES (coach_id) ON DELETE SET NULL
) TABLESPACE sportics_ts;


-- 7. Таблица записи клиентов на занятия
CREATE TABLE CLIENT_SESSION_RECORDS (
    record_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id    NUMBER NOT NULL,
    schedule_id  NUMBER NOT NULL,
    attendance_date DATE,
    performance_notes VARCHAR2(200),
    attended     CHAR(1) CHECK (attended IN ('Y','N')),
    CONSTRAINT fk_record_client FOREIGN KEY (client_id)
        REFERENCES CLIENTS (client_id) ON DELETE CASCADE,
    CONSTRAINT fk_record_schedule FOREIGN KEY (schedule_id)
        REFERENCES SCHEDULES (schedule_id) ON DELETE CASCADE,
    CONSTRAINT uq_client_schedule UNIQUE (client_id, schedule_id)
) TABLESPACE sportics_ts;


COMMIT;


DROP TABLE USERS PURGE;
DROP TABLE CLIENTS PURGE;
DROP TABLE COACHES PURGE;
DROP TABLE MEMBERSHIPS PURGE;
DROP TABLE MEMBERSHIP_ORDERS PURGE;
DROP TABLE SCHEDULES PURGE;
DROP TABLE CLIENT_SESSION_RECORDS PURGE;