-- 1
SELECT * FROM V$SGA;

SELECT * FROM V$SGA_DYNAMIC_COMPONENTS;


-- 2
SELECT * FROM V$PARAMETER;


-- 3
SELECT * FROM V$CONTROLFILE;


-- 4
CREATE PFILE = 'pfileXE.ora' FROM SPFILE;


-- 5
CREATE TABLE TEST_TABLE (
    ID NUMBER PRIMARY KEY,
    VALUE NVARCHAR2(50)
);

DROP TABLE TEST_TABLE CASCADE CONSTRAINTS;

SELECT * FROM USER_SEGMENTS 
WHERE SEGMENT_NAME = 'TEST_TABLE';

INSERT INTO TEST_TABLE VALUES (1, 'Test1');
INSERT INTO TEST_TABLE VALUES (2, 'Test2');

SELECT * FROM USER_EXTENTS 
WHERE SEGMENT_NAME = 'TEST_TABLE';


-- 6
SELECT * FROM V$PROCESS;

SELECT SID, SERIAL#, USERNAME, SERVER 
FROM V$SESSION WHERE TYPE = 'USER';

SELECT SID, SERIAL#, PROGRAM, STATUS, SERVER 
FROM V$SESSION WHERE TYPE = 'BACKGROUND';


-- 7
SELECT * FROM DBA_TABLESPACES;

SELECT T.TABLESPACE_NAME, F.FILE_NAME 
FROM DBA_TABLESPACES T
JOIN DBA_DATA_FILES F
ON T.TABLESPACE_NAME = F.TABLESPACE_NAME;


-- 8
SELECT * FROM DBA_ROLES;


-- 9
SELECT * FROM DBA_SYS_PRIVS 
WHERE GRANTEE = 'CONNECT';


-- 10
SELECT * FROM DBA_USERS;


-- 11
CREATE ROLE TEST_ROLE;

GRANT CREATE SESSION TO TEST_ROLE;
GRANT CREATE TABLE TO TEST_ROLE;


-- 12
CREATE USER TEST_USER IDENTIFIED BY 12345
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON USERS;

GRANT TEST_ROLE TO TEST_USER;


-- 13
SELECT DISTINCT PROFILE FROM DBA_PROFILES;


-- 14
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';


-- 15
CREATE PROFILE SECURE_PROFILE
LIMIT
    SESSIONS_PER_USER 2
    CONNECT_TIME 60
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90;
    
ALTER USER TEST_USER PROFILE SECURE_PROFILE;


-- 16
CREATE SEQUENCE S1
START WITH 1000
INCREMENT BY 1000
MINVALUE 0
MAXVALUE 10000
CYCLE
CACHE 30
ORDER;

CREATE TABLE T1 (
    ID NUMBER PRIMARY KEY,
    VALUE1 NUMBER,
    VALUE2 DATE
);

BEGIN
    FOR i IN 1..10 LOOP
        INSERT INTO T1 VALUES (S1.NEXTVAL, i, SYSDATE);
    END LOOP;
    COMMIT;
END;


-- 17
CREATE SYNONYM T1_PRIV FOR T1;

CREATE PUBLIC SYNONYM T1_PUB FOR T1;

SELECT * FROM USER_SYNONYMS;

SELECT * FROM DBA_SYNONYMS WHERE OWNER = 'PUBLIC';


-- 18
DECLARE
    v_id T1.id%TYPE;
BEGIN
    SELECT id INTO v_id
    FROM T1
    WHERE value1 > 0;
    
    DBMS_OUTPUT.PUT_LINE('ID = ' || v_id);
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Данные не найдены');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('Найдено более одной строки');
END;


-- 19
SELECT * FROM V$LOGFILE;


-- 20
SELECT * FROM V$LOG
WHERE STATUS = 'CURRENT';


-- 21
SELECT * FROM V$CONTROLFILE;


-- 22
CREATE TABLE TEST_TABLE (
    ID NUMBER PRIMARY KEY,
    VALUE NVARCHAR2(50)
);

DROP TABLE TEST_TABLE CASCADE CONSTRAINTS;

BEGIN
    FOR i IN 1..100 LOOP
        INSERT INTO TEST_TABLE VALUES (i, 'Row ' || i);
    END LOOP;
    COMMIT;
END;

SELECT * FROM USER_TABLES 
WHERE TABLE_NAME = 'TEST_TABLE';


-- 23
SELECT * FROM DBA_SEGMENTS
WHERE TABLESPACE_NAME = 'SYSTEM';


-- 24
SELECT * FROM USER_OBJECTS;


-- 25
SELECT BLOCKS FROM USER_EXTENTS 
WHERE SEGMENT_NAME = 'TEST_TABLE';


-- 26
SELECT * FROM V$SESSION
WHERE USERNAME IS NOT NULL;


-- 27
SELECT LOG_MODE FROM V$DATABASE;


-- 28
CREATE VIEW TEST_VIEW
AS
SELECT ID, VALUE
FROM TEST_TABLE
WHERE id < 10
WITH READ ONLY;


-- 29
CREATE DATABASE LINK REMOTE_DB
CONNECT TO ZAI IDENTIFIED BY 12345
USING 'ZAI_USER';

SELECT * FROM DUAL@REMOTE_DB;


-- 30
DECLARE
    v NUMBER;
BEGIN
    BEGIN
        v:= 10 / 0;
    EXCEPTION
        WHEN ZERO_DIVIDE THEN
            DBMS_OUTPUT.PUT_LINE('Ошибка деления');
            RAISE;
    END;
END;
