// 1
ALTER SESSION SET CONTAINER = CDB$ROOT;

SHOW CON_NAME;

SELECT NAME, OPEN_MODE, RESTRICTED
FROM V$PDBS;


// 2
SELECT INSTANCE_NAME, STATUS, VERSION, HOST_NAME
FROM V$INSTANCE;


// 3
SELECT COMP_NAME, VERSION, STATUS
FROM DBA_REGISTRY;


// 4
CREATE PLUGGABLE DATABASE ZAI_PDB
    ADMIN USER PDB_ADMIN IDENTIFIED BY 12345
    ROLES = (DBA)
    FILE_NAME_CONVERT = ('/opt/oracle/oradata/XE/',
                        '/opt/oracle/oradata/XE/ZAI_PDB/');

ALTER PLUGGABLE DATABASE ZAI_PDB OPEN;


// 5
SELECT NAME, OPEN_MODE, RESTRICTED
FROM V$PDBS;


// 6
ALTER SESSION SET CONTAINER = ZAI_PDB;

CREATE TABLESPACE TS_ZAI_PDB
    DATAFILE 'TS_ZAI_PDB.dbf'
    SIZE 7 m
    AUTOEXTEND ON NEXT 5 m
    MAXSIZE 20 m
    EXTENT MANAGEMENT LOCAL;
    
DROP TABLESPACE TS_ZAI_PDB INCLUDING CONTENTS AND DATAFILES;

CREATE TEMPORARY TABLESPACE TS_ZAI_PDB_TEMP
    TEMPFILE 'TS_ZAI_PDB_TEMP.dbf'
    SIZE 5 m
    AUTOEXTEND ON NEXT 3 m
    MAXSIZE 30 m
    EXTENT MANAGEMENT LOCAL;
    
DROP TABLESPACE TS_ZAI_PDB_TEMP INCLUDING CONTENTS AND DATAFILES;

CREATE ROLE RL_ZAIPDB;
GRANT CREATE SESSION,
        CREATE TABLE,
        CREATE TABLESPACE,
        CREATE VIEW,
        CREATE PROCEDURE,
        DROP ANY TABLE,
        DROP TABLESPACE,
        DROP ANY VIEW,
        DROP ANY PROCEDURE TO RL_ZAIPDB;
        
DROP ROLE RL_ZAIPDB;

CREATE PROFILE PF_ZAIPDB LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

DROP PROFILE PF_ZAIPDB CASCADE;

CREATE USER U1_ZAI_PDB IDENTIFIED BY 12345
    DEFAULT TABLESPACE TS_ZAI_PDB QUOTA UNLIMITED ON TS_ZAI_PDB
    TEMPORARY TABLESPACE TS_ZAI_PDB_TEMP
    PROFILE PF_ZAIPDB
    ACCOUNT UNLOCK;

GRANT RL_ZAIPDB TO U1_ZAI_PDB;

REVOKE RL_ZAIPDB FROM U1_ZAI_PDB;

DROP USER U1_ZAI_PDB;


// 7
CREATE TABLE ZAI_table (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50)
);

INSERT INTO ZAI_table VALUES (1, 'Первый');
INSERT INTO ZAI_table VALUES (2, 'Второй');
COMMIT;

SELECT * FROM ZAI_table;

DROP TABLE ZAI_table;


// 8
SELECT TABLESPACE_NAME FROM DBA_TABLESPACES;

SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_DATA_FILES
UNION ALL
SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_TEMP_FILES;

SELECT ROLE FROM DBA_ROLES;

SELECT * FROM DBA_ROLE_PRIVS;

SELECT PROFILE FROM DBA_PROFILES;

SELECT USERNAME, profile FROM DBA_USERS;


// 9
ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE USER C##ZAI IDENTIFIED BY 12345 CONTAINER = ALL;
GRANT CREATE SESSION TO C##ZAI CONTAINER = ALL;

SHOW CON_NAME;


// 10
ALTER SESSION SET CONTAINER = CDB$ROOT;

ALTER PLUGGABLE DATABASE ZAI_PDB CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE ZAI_PDB INCLUDING DATAFILES;

DROP USER C##ZAI CASCADE;

