-- 1
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE ZAI_QDATA
    DATAFILE 'ZAI_QDATA.dbf' 
    SIZE 10M
    OFFLINE;

ALTER DATABASE DATAFILE 'ZAI_QDATA.dbf' ONLINE;
ALTER TABLESPACE ZAI_QDATA ONLINE;

DROP TABLESPACE ZAI_QDATA INCLUDING CONTENTS AND DATAFILES;


CREATE PROFILE PF_ZAI LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

DROP PROFILE PF_ZAI CASCADE;


CREATE USER ZAI IDENTIFIED BY 12345
    DEFAULT TABLESPACE ZAI_QDATA QUOTA 2M ON ZAI_QDATA
    PROFILE PF_ZAI
    ACCOUNT UNLOCK;

GRANT CREATE SESSION TO ZAI;
GRANT CREATE TABLE TO ZAI;
GRANT CREATE SEQUENCE TO ZAI;
GRANT CREATE CLUSTER TO ZAI;
GRANT CREATE VIEW TO ZAI;
GRANT CREATE SYNONYM TO ZAI;
GRANT CREATE MATERIALIZED VIEW TO ZAI;
GRANT CREATE PROCEDURE TO ZAI;
GRANT CREATE PUBLIC SYNONYM TO ZAI;
GRANT DROP PUBLIC SYNONYM TO ZAI;
GRANT UNLIMITED TABLESPACE TO ZAI;

DROP USER ZAI;


-- 2
CREATE SEQUENCE S1
  START WITH 1000
  INCREMENT BY 10
  NOMINVALUE
  NOMAXVALUE
  NOCYCLE
  NOCACHE
  NOORDER;
  
SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.NEXTVAL FROM DUAL;

SELECT S1.CURRVAL FROM DUAL;

DROP SEQUENCE S1;


-- 3
CREATE SEQUENCE S2
  START WITH 10
  INCREMENT BY 10
  MAXVALUE 100
  NOCYCLE
  NOCACHE
  NOORDER;


-- 4
SELECT S2.NEXTVAL FROM DUAL;
SELECT S2.NEXTVAL FROM DUAL;
SELECT S2.NEXTVAL FROM DUAL;
SELECT S2.NEXTVAL FROM DUAL;
SELECT S2.NEXTVAL FROM DUAL;
SELECT S2.NEXTVAL FROM DUAL;
SELECT S2.NEXTVAL FROM DUAL;
SELECT S2.NEXTVAL FROM DUAL;
SELECT S2.NEXTVAL FROM DUAL;
SELECT S2.NEXTVAL FROM DUAL;
SELECT S2.NEXTVAL FROM DUAL;

DROP SEQUENCE S2;


-- 5
CREATE SEQUENCE S3
  START WITH 10
  INCREMENT BY -10
  MINVALUE -100
  MAXVALUE 10
  NOCYCLE
  NOCACHE
  ORDER;
  
SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.NEXTVAL FROM DUAL;

DROP SEQUENCE S3;


-- 6
CREATE SEQUENCE S4
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 10
  CYCLE
  CACHE 5
  NOORDER;

SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.NEXTVAL FROM DUAL;

DROP SEQUENCE S4;


-- 7
SELECT sequence_name, min_value, max_value, increment_by, cycle_flag, cache_size, order_flag
FROM user_sequences
ORDER BY sequence_name;


-- 8
CREATE TABLE T1 (
  n1 NUMBER(20),
  n2 NUMBER(20),
  n3 NUMBER(20),
  n4 NUMBER(20)
)
CACHE
STORAGE ( BUFFER_POOL KEEP );

BEGIN
  FOR i IN 1..7 LOOP
    INSERT INTO T1 (n1,n2,n3,n4)
    VALUES (
      S1.NEXTVAL,
      S2.NEXTVAL,
      S3.NEXTVAL,
      S4.NEXTVAL
    );
  END LOOP;
  COMMIT;
END;

SELECT * FROM T1;

DROP TABLE T1;


-- 9
CREATE CLUSTER ABC (
  x NUMBER(10),
  v VARCHAR2(12)
) HASHKEYS 200;

DROP CLUSTER ABC;


-- 10
CREATE TABLE A (
  xa NUMBER(10),
  va VARCHAR2(12),
  extra_a VARCHAR2(50)
) CLUSTER ABC (xa, va);

DROP TABLE A;


-- 11
CREATE TABLE B (
  xb NUMBER(10),
  vb VARCHAR2(12),
  extra_b VARCHAR2(50)
) CLUSTER ABC (xb, vb);

DROP TABLE B;


-- 12
CREATE TABLE C (
  xc NUMBER(10),
  vc VARCHAR2(12),
  extra_c VARCHAR2(50)
) CLUSTER ABC (xc, vc);

DROP TABLE C;


INSERT INTO A VALUES (1, 'A1', 'extraA1');
INSERT INTO A VALUES (2, 'A2', 'extraA2');

INSERT INTO B VALUES (1, 'B1', 'extraB1');
INSERT INTO B VALUES (3, 'B3', 'extraB3');

INSERT INTO C VALUES (1, 'C1', 'extraC1');
COMMIT;


-- 13
SELECT table_name FROM user_tables ORDER BY table_name;

SELECT cluster_name FROM user_clusters;


-- 14
CREATE SYNONYM MY_C FOR ZAI.C;

SELECT * FROM MY_C;

DROP SYNONYM MY_C;


-- 15
CREATE PUBLIC SYNONYM PB FOR ZAI.B;

SELECT * FROM PB;

DROP PUBLIC SYNONYM PB;


-- 16
CREATE TABLE A (
  id NUMBER PRIMARY KEY,
  name VARCHAR2(50)
);

DROP TABLE A;

CREATE TABLE B (
  id NUMBER PRIMARY KEY,
  a_id NUMBER,
  descr VARCHAR2(100),
  CONSTRAINT FK_B_A FOREIGN KEY (a_id) REFERENCES A(id)
);

DROP TABLE B;

INSERT INTO A (id,name) VALUES (1,'Alpha');
INSERT INTO A (id,name) VALUES (2,'Beta');

INSERT INTO B (id,a_id,descr) VALUES (10,1,'descr for alpha');
INSERT INTO B (id,a_id,descr) VALUES (11,2,'descr for beta');
COMMIT;

CREATE OR REPLACE VIEW V1 AS
SELECT a.id AS a_id, a.name AS a_name, b.id AS b_id, b.descr
FROM A a
JOIN B b ON a.id = b.a_id;

SELECT * FROM V1;

DROP VIEW V1;


-- 17
CREATE MATERIALIZED VIEW MV
REFRESH COMPLETE
START WITH SYSDATE
NEXT SYSDATE + (2/1440)
AS
SELECT a.id AS a_id, a.name AS a_name, b.id AS b_id, b.descr
FROM A a
JOIN B b ON a.id = b.a_id;

SELECT * FROM MV;

INSERT INTO B (id, a_id, descr) VALUES (12, 1, 'new row');
COMMIT;

DROP MATERIALIZED VIEW MV;





