ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE TABLESPACE ZAI_QDATA
    DATAFILE 'ZAI_QDATA.dbf' 
    SIZE 60M
    OFFLINE;
    
ALTER TABLESPACE ZAI_QDATA
    ADD DATAFILE 'ZAI_QDATA_EXTEND.dbf'
    SIZE 50M
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE 'ZAI_QDATA.dbf' ONLINE;
ALTER TABLESPACE ZAI_QDATA ONLINE;

DROP TABLESPACE ZAI_QDATA INCLUDING CONTENTS AND DATAFILES;


CREATE PROFILE PF_ZAI LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

DROP PROFILE PF_ZAI CASCADE;


CREATE USER ZAI IDENTIFIED BY 12345
    DEFAULT TABLESPACE ZAI_QDATA QUOTA 2M ON ZAI_QDATA
    PROFILE PF_ZAI
    ACCOUNT UNLOCK;

GRANT CREATE SESSION TO ZAI;
GRANT RESTRICTED SESSION TO ZAI;
GRANT CREATE ANY TABLE TO ZAI;
GRANT CREATE ANY VIEW TO ZAI;
GRANT CREATE SEQUENCE TO ZAI;
GRANT UNLIMITED TABLESPACE TO ZAI;
GRANT CREATE TABLESPACE TO ZAI;
GRANT DROP TABLESPACE TO ZAI;
GRANT CREATE CLUSTER TO ZAI;
GRANT CREATE SYNONYM TO ZAI;
GRANT CREATE PUBLIC SYNONYM TO ZAI;
GRANT CREATE MATERIALIZED VIEW TO ZAI;
GRANT CREATE ANY PROCEDURE TO ZAI;
GRANT CREATE TYPE TO ZAI;
GRANT CREATE TRIGGER TO ZAI;


DROP USER ZAI;


--1.Создайте таблицу, имеющую несколько атрибутов, один из которых первичный
--ключ.
CREATE TABLE TEST_TABLE(
    A INT PRIMARY KEY,
    B VARCHAR(30)
);

DROP TABLE TEST_TABLE PURGE;

--2. Заполните таблицу строками (10 шт.).

BEGIN
    FOR I IN 21..30
    LOOP
        INSERT INTO TEST_TABLE VALUES (I, 'A' || TO_CHAR(I));
    END LOOP;
END;

INSERT ALL
INTO TEST_TABLE VALUES (99, 'A' || TO_CHAR(99))
INTO TEST_TABLE VALUES (100, 'A' || TO_CHAR(100))
SELECT * FROM DUAL;
        
UPDATE TEST_TABLE
SET B = 'MEOW'
WHERE A = 99 OR A = 100;
        
DELETE FROM TEST_TABLE WHERE A=99 OR A = 100;

SELECT * FROM TEST_TABLE;

--3,4, 6. Создайте BEFORE – триггер уровня оператора на события INSERT, DELETE и
--UPDATE.

CREATE OR REPLACE TRIGGER TEST_BEFORE_TRIGGER_STATEMENT
BEFORE INSERT OR DELETE OR UPDATE ON TEST_TABLE
BEGIN
    DBMS_OUTPUT.PUT_LINE('BEFORE TRIGGER STATEMENT ZAI');
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('INSERT operation');
        INSERT INTO AUDIT_ VALUES (SYSDATE, 'INSERT', 'TEST_BEFORE_TRIGGER_STATEMENT', 'NO DATA');
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('UPDATE operation');
        INSERT INTO AUDIT_ VALUES (SYSDATE, 'UPDATE', 'TEST_BEFORE_TRIGGER_STATEMENT', 'NO DATA');
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('DELETE operation');
        INSERT INTO AUDIT_ VALUES (SYSDATE, 'DELETE', 'TEST_BEFORE_TRIGGER_STATEMENT', 'NO DATA');
    END IF;
END;

--5,6. Создайте BEFORE-триггер уровня строки на события INSERT, DELETE и
--UPDATE.

CREATE OR REPLACE TRIGGER TEST_BEFORE_TRIGGER_ROW
BEFORE INSERT OR DELETE OR UPDATE ON TEST_TABLE
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('BEFORE TRIGGER EACH ROW ZAI');
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('INSERT operation');
        INSERT INTO AUDIT_ VALUES (SYSDATE, 'INSERT', 'TEST_BEFORE_TRIGGER_ROW', ' ' || :NEW.A || ', ' || :NEW.B);
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('UPDATE operation');
        INSERT INTO AUDIT_ VALUES (SYSDATE, 'UPDATE', 'TEST_BEFORE_TRIGGER_ROW', ' ' || :OLD.A || ', ' || :OLD.B || :NEW.A || ', ' || :NEW.B);
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('DELETE operation');
        INSERT INTO AUDIT_ VALUES (SYSDATE, 'DELETE', 'TEST_BEFORE_TRIGGER_ROW', ' ' || :NEW.A || ', ' || :NEW.B);
    END IF;
END;

--7. Разработайте AFTER-триггеры уровня оператора на события INSERT, DELETE и
--UPDATE.

CREATE OR REPLACE TRIGGER TEST_AFTER_TRIGGER_STATEMENT
AFTER INSERT OR DELETE OR UPDATE ON TEST_TABLE
BEGIN
    DBMS_OUTPUT.PUT_LINE('AFTER TRIGGER STATEMENT ZAI');
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('INSERT operation');
        INSERT INTO AUDIT_ VALUES (SYSDATE, 'INSERT', 'TEST_AFTER_TRIGGER_STATEMENT', 'NO DATA');
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('UPDATE operation');
        INSERT INTO AUDIT_ VALUES (SYSDATE, 'UPDATE', 'TEST_AFTER_TRIGGER_STATEMENT', 'NO DATA');
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('DELETE operation');
        INSERT INTO AUDIT_ VALUES (SYSDATE, 'DELETE', 'TEST_AFTER_TRIGGER_STATEMENT', 'NO DATA');
    END IF;
END;




--8. Разработайте AFTER-триггеры уровня строки на события INSERT, DELETE и
--UPDATE.

CREATE OR REPLACE TRIGGER TEST_AFTER_TRIGGER_ROW
AFTER INSERT OR DELETE OR UPDATE ON TEST_TABLE
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('AFTER TRIGGER EACH ROW ZAI');
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('INSERT operation');
        INSERT INTO AUDIT_ VALUES (SYSDATE, 'INSERT', 'TEST_AFTER_TRIGGER_ROW', ' ' || :NEW.A || ', ' || :NEW.B);
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('UPDATE operation');
        INSERT INTO AUDIT_ VALUES (SYSDATE, 'UPDATE', 'TEST_AFTER_TRIGGER_ROW', ' ' || :OLD.A || ', ' || :OLD.B || :NEW.A || ', ' || :NEW.B);
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('DELETE operation');
        INSERT INTO AUDIT_ VALUES (SYSDATE, 'DELETE', 'TEST_AFTER_TRIGGER_ROW', ' ' || :NEW.A || ', ' || :NEW.B);
    END IF;
END;


--9

CREATE TABLE AUDIT_ (
    OPERATIONDATE DATE,
    OPERATIONTYPE VARCHAR2(50),
    TRIGGERNAME   VARCHAR2(50),
    DATA          VARCHAR2(40)
);

SELECT * FROM AUDIT_;

DROP TABLE AUDIT_ PURGE;


--11 Выполните операцию, нарушающую целостность таблицы по первичному ключу.
--Выясните, зарегистрировал ли триггер это событие. Объясните результат.
INSERT INTO TEST_TABLE VALUES (101, 'A101');

select * from DBA_TRIGGERS where OWNER = 'ZAI';


--12 Удалите (drop) исходную таблицу. Объясните результат. Добавьте триггер,
--запрещающий удаление исходной таблицы.

DROP TABLE TEST_TABLE;

FLASHBACK TABLE TEST_TABLE TO BEFORE DROP;

CREATE OR REPLACE TRIGGER BEFORE_DROP 
BEFORE DROP ON SCHEMA
BEGIN 
    IF ORA_DICT_OBJ_NAME <> 'TEST_TABLE' THEN
        RETURN;
    END IF;
    
    RAISE_APPLICATION_ERROR(-20001, 'Нельзя удалять таблицу TEST_TABLE');
END;
    
--13. Удалите (drop) таблицу AUDIT. Просмотрите состояние триггеров с помощью
--SQL-DEVELOPER. Объясните результат. Измените триггеры.

DROP TABLE AUDIT_ PURGE;
    
select TRIGGER_NAME, STATUS from USER_TRIGGERS;

--14. Создайте представление над исходной таблицей. Разработайте INSTEADOF
--INSERT-триггер. Триггер должен добавлять строку в таблицу.


CREATE VIEW TEST_VIEW
AS
SELECT * FROM TEST_TABLE;

CREATE OR REPLACE TRIGGER TEST_VIEW_TRIGGER
  INSTEAD OF INSERT ON TEST_VIEW
BEGIN
    INSERT INTO AUDIT_ VALUES (SYSDATE, 'INSERT', 'TEST_VIEW_TRIGGER', :NEW.A || ', ' || :NEW.B);
    INSERT INTO TEST_TABLE VALUES (:NEW.A, :NEW.B);
END;

INSERT INTO TEST_VIEW VALUES (102, 'A102');
DELETE FROM TEST_TABLE WHERE A = 102;

DROP VIEW TEST_VIEW;

--15. Продемонстрируйте, в каком порядке выполняются триггеры.

DROP TRIGGER TEST_VIEW_TRIGGER;
DROP TRIGGER BEFORE_DROP;
DROP TRIGGER TEST_AFTER_TRIGGER_ROW;
DROP TRIGGER TEST_AFTER_TRIGGER_STATEMENT;
DROP TRIGGER TEST_BEFORE_TRIGGER_ROW;
DROP TRIGGER TEST_BEFORE_TRIGGER_STATEMENT;