
drop tablespace table_space_1 including contents and datafiles;
drop tablespace table_space_2 including contents and datafiles;
drop tablespace table_space_3 including contents and datafiles;
drop tablespace table_space_4 including contents and datafiles;
 
CREATE TABLESPACE TABLE_SPACE_1
    DATAFILE 'TABLE_SPACE_1.dbf' SIZE 7 M AUTOEXTEND ON
    MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TABLE_SPACE_2
    DATAFILE 'TABLE_SPACE_2.dbf' SIZE 7 M AUTOEXTEND ON
    MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TABLE_SPACE_3
    DATAFILE 'TABLE_SPACE_3.dbf' SIZE 7 M AUTOEXTEND ON
    MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TABLE_SPACE_4
    DATAFILE 'TABLE_SPACE_4.dbf' SIZE 7 M AUTOEXTEND ON
    MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;


--1. Создайте таблицу T_RANGE c диапазонным секционированием. Используйте ключ
--секционирования типа NUMBER.
DROP TABLE T_RANGE PURGE;
DROP TABLE T_INTERVAL PURGE;
DROP TABLE T_HASH PURGE;
DROP TABLE T_LIST PURGE;

CREATE TABLE T_RANGE(
    ID NUMBER,
    VALUE VARCHAR2(100)
)
PARTITION BY RANGE (ID) (
    PARTITION P0 VALUES LESS THAN (100) TABLESPACE TABLE_SPACE_1,
    PARTITION P1 VALUES LESS THAN (200) TABLESPACE TABLE_SPACE_2,
    PARTITION P2 VALUES LESS THAN (300) TABLESPACE TABLE_SPACE_3,
    PARTITION P3 VALUES LESS THAN (MAXVALUE) TABLESPACE TABLE_SPACE_4
);

--2.Создайте таблицу T_INTERVAL c интервальным секционированием. Используйте
--ключ секционирования типа DATE.

CREATE TABLE T_INTERVAL(
    ENTRY_DATE DATE,
    VALUE VARCHAR2(100)
)
PARTITION BY RANGE (ENTRY_DATE) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P0 VALUES LESS THAN (TO_DATE('1.12.2010', 'DD-MM-YYYY')) TABLESPACE TABLE_SPACE_1,
    PARTITION P1 VALUES LESS THAN (TO_DATE('1.12.2015', 'DD-MM-YYYY')) TABLESPACE TABLE_SPACE_2,
    PARTITION P2 VALUES LESS THAN (TO_DATE('1.12.2020', 'DD-MM-YYYY')) TABLESPACE TABLE_SPACE_3
);

--3. Создайте таблицу T_HASH c хэш-секционированием. Используйте ключ
--секционирования типа VARCHAR2.

CREATE TABLE T_HASH(
    NAME VARCHAR2(100),
    VALUE  NUMBER
)
PARTITION BY HASH (NAME) (
    PARTITION P0 TABLESPACE TABLE_SPACE_1,
    PARTITION P1 TABLESPACE TABLE_SPACE_2,
    PARTITION P2 TABLESPACE TABLE_SPACE_3,
    PARTITION P3 TABLESPACE TABLE_SPACE_4
);

--4. Создайте таблицу T_LIST со списочным секционированием. Используйте ключ
--секционирования типа CHAR.

CREATE TABLE T_LIST(
    OBJ CHAR(3)
)
PARTITION BY LIST(OBJ) (
    PARTITION L0 VALUES ('A') TABLESPACE TABLE_SPACE_1,
    PARTITION L1 VALUES ('B') TABLESPACE TABLE_SPACE_2,
    PARTITION L2 VALUES ('C') TABLESPACE TABLE_SPACE_3,
    PARTITION L3 VALUES (DEFAULT) TABLESPACE TABLE_SPACE_4
);

--5. Введите с помощью операторов INSERT данные в таблицы T_RANGE,
--T_INTERVAL, T_HASH, T_LIST. Данные должны быть такими, чтобы они
--разместились по всем секциям. Продемонстрируйте это с помощью SELECT запроса

INSERT INTO T_RANGE VALUES (50, 'Секция P0');
INSERT INTO T_RANGE VALUES (150, 'Секция P1');
INSERT INTO T_RANGE VALUES (250, 'Секция P2');
INSERT INTO T_RANGE VALUES (350, 'Секция P3');
INSERT INTO T_RANGE VALUES (2000, 'Секция P3');

SELECT * FROM T_RANGE PARTITION(P0);
SELECT * FROM T_RANGE PARTITION(P1);
SELECT * FROM T_RANGE PARTITION(P2);
SELECT * FROM T_RANGE PARTITION(P3);

SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE, TABLESPACE_NAME FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_RANGE';

INSERT INTO T_INTERVAL VALUES (TO_DATE('01.02.2008', 'DD.MM.YYYY'), 'P0');
INSERT INTO T_INTERVAL VALUES (TO_DATE('01-01-2009', 'DD.MM.YYYY'), 'P0');
INSERT INTO T_INTERVAL VALUES (TO_DATE('01-01-2007', 'DD.MM.YYYY'), 'P0');
INSERT INTO T_INTERVAL VALUES (TO_DATE('01-01-2019', 'DD.MM.YYYY'), 'P2');
INSERT INTO T_INTERVAL VALUES (TO_DATE('01-01-2013', 'DD.MM.YYYY'), 'P1');
INSERT INTO T_INTERVAL VALUES (TO_DATE('01-01-2017', 'DD.MM.YYYY'), 'P2');

INSERT INTO T_INTERVAL VALUES (TO_DATE('01-01-2022', 'DD.MM.YYYY'), 'SYS_P824');


SELECT * FROM T_INTERVAL PARTITION (P0);
SELECT * FROM T_INTERVAL PARTITION (P1);
SELECT * FROM T_INTERVAL PARTITION (P2);
SELECT * FROM T_INTERVAL PARTITION (SYS_P825);

SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE, TABLESPACE_NAME FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_INTERVAL';


INSERT INTO T_HASH VALUES ('abc', 100);
INSERT INTO T_HASH VALUES ('qwe', 200);
INSERT INTO T_HASH VALUES ('zxc', 300);
INSERT INTO T_HASH VALUES ('dov', 400);
INSERT INTO T_HASH VALUES ('gaw', 400);


SELECT * FROM T_HASH PARTITION (P0);
SELECT * FROM T_HASH PARTITION (P1);
SELECT * FROM T_HASH PARTITION (P2);
SELECT * FROM T_HASH PARTITION (P3);

SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE, TABLESPACE_NAME FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_HASH';

INSERT INTO T_LIST(OBJ) VALUES('A');
INSERT INTO T_LIST(OBJ) VALUES('B');
INSERT INTO T_LIST(OBJ) VALUES('C');
INSERT INTO T_LIST(OBJ) VALUES('D');
INSERT INTO T_LIST(OBJ) VALUES('E');

SELECT * FROM T_LIST PARTITION (L0);
SELECT * FROM T_LIST PARTITION (L1);
SELECT * FROM T_LIST PARTITION (L2);
SELECT * FROM T_LIST PARTITION (L3);

SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE, TABLESPACE_NAME FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_LIST';

--6. Продемонстрируйте для всех таблиц процесс перемещения строк между секциями,
--при изменении (оператор UPDATE) ключа секционирования.

ALTER TABLE T_RANGE ENABLE ROW MOVEMENT;
SELECT * FROM T_RANGE PARTITION(P3);

UPDATE T_RANGE SET ID=2 WHERE ID=2000;
SELECT * FROM T_RANGE PARTITION(P0) ORDER BY ID;

ALTER TABLE T_INTERVAL ENABLE ROW MOVEMENT;
SELECT * FROM T_INTERVAL PARTITION(P1);

UPDATE T_INTERVAL SET ENTRY_DATE = TO_DATE('01.02.2017', 'DD.MM.YYYY') WHERE VALUE = 'P0';
SELECT * FROM T_INTERVAL PARTITION(P2);

ALTER TABLE T_HASH ENABLE ROW MOVEMENT;
SELECT * FROM T_HASH PARTITION(P2);

UPDATE T_HASH SET NAME='ba' WHERE NAME = 'qwe';
SELECT * FROM T_HASH PARTITION(P1);

ALTER TABLE T_LIST ENABLE ROW MOVEMENT;
SELECT * FROM T_LIST PARTITION(L0);

UPDATE T_LIST SET OBJ='B' WHERE OBJ='A';
SELECT * FROM T_LIST PARTITION(L1);

--7. Для одной из таблиц продемонстрируйте действие оператора ALTER TABLE
--MERGE.

ALTER TABLE T_RANGE MERGE PARTITIONS P2, P3 INTO PARTITION P_MERGED;
SELECT * FROM T_RANGE PARTITION(P_MERGED);

--8. Для одной из таблиц продемонстрируйте действие оператора ALTER TABLE SPLIT.

ALTER TABLE T_RANGE SPLIT PARTITION P_MERGED AT (300)
INTO (PARTITION P2 TABLESPACE TABLE_SPACE_2, PARTITION P3 TABLESPACE TABLE_SPACE_3);

SELECT * FROM T_RANGE PARTITION(P2);
SELECT * FROM T_RANGE PARTITION(P3);

--9 Для одной из таблиц продемонстрируйте действие оператора ALTER TABLE
--EXCHANGE.

DROP TABLE T_RANGE1 PURGE;

CREATE TABLE T_RANGE1 (
    ID NUMBER,
    VALUE VARCHAR2(100)
);

ALTER TABLE T_RANGE EXCHANGE PARTITION P0 WITH TABLE T_RANGE1 WITHOUT VALIDATION;

SELECT * FROM T_RANGE PARTITION (P0);
SELECT * FROM T_RANGE1;