-- 1
SELECT SUM(CURRENT_SIZE) AS SGA_CURRENT_BYTES
FROM   V$SGA_DYNAMIC_COMPONENTS;


-- 2
SELECT COMPONENT, CURRENT_SIZE
FROM   V$SGA_DYNAMIC_COMPONENTS
ORDER BY COMPONENT;


-- 3
SELECT COMPONENT, GRANULE_SIZE
FROM   V$SGA_DYNAMIC_COMPONENTS
GROUP BY COMPONENT, GRANULE_SIZE
ORDER BY COMPONENT;


-- 4
SELECT *
FROM   V$SGASTAT
WHERE  NAME LIKE '%free memory%';

SELECT SUM(BYTES) AS FREE_BYTES
FROM   V$SGASTAT
WHERE  NAME LIKE '%free memory%';


-- 5
SELECT NAME, VALUE
FROM   V$PARAMETER
WHERE  NAME IN ('sga_target','sga_max_size');


-- 6
SELECT COMPONENT, CURRENT_SIZE
FROM   V$SGA_DYNAMIC_COMPONENTS
WHERE  UPPER(COMPONENT) LIKE '%BUFFER CACHE%' OR UPPER(COMPONENT) LIKE '%BUFFER%';


-- 7
CREATE TABLE T_KEEP (
  id    NUMBER PRIMARY KEY,
  data  VARCHAR2(4000)
)
STORAGE (BUFFER_POOL KEEP);

SELECT OWNER, SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, BYTES, BLOCKS
FROM   DBA_SEGMENTS
WHERE  SEGMENT_NAME = 'T_KEEP';

SELECT table_name, buffer_pool
FROM   dba_tables
WHERE  table_name = 'T_KEEP';

DROP TABLE T_KEEP;


-- 8
CREATE TABLE T_DEFAULT (
  id   NUMBER PRIMARY KEY,
  info VARCHAR2(2000)
)
STORAGE (BUFFER_POOL DEFAULT);

SELECT OWNER, SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, BYTES, BLOCKS
FROM   DBA_SEGMENTS
WHERE  SEGMENT_NAME = 'T_DEFAULT';

SELECT table_name, buffer_pool
FROM   dba_tables
WHERE  table_name = 'T_DEFAULT';

DROP TABLE T_DEFAULT;


-- 9
SELECT NAME, VALUE
FROM   V$PARAMETER
WHERE  NAME = 'log_buffer';


-- 10
SELECT COMPONENT, CURRENT_SIZE
FROM   V$SGA_DYNAMIC_COMPONENTS
WHERE  UPPER(COMPONENT) LIKE '%LARGE%';

SELECT *
FROM   V$SGASTAT
WHERE  NAME LIKE '%free memory%' AND POOL LIKE '%large pool%';


-- 11
SELECT SERVER, COUNT(*) AS COUNT
FROM   V$SESSION
GROUP BY SERVER;


-- 12
SELECT *
FROM   V$BGPROCESS
ORDER BY NAME;


-- 13
SELECT S.SID, S.SERIAL#, S.USERNAME, P.SPID AS OS_PID, P.PROGRAM
FROM   V$SESSION S
JOIN   V$PROCESS P ON S.PADDR = P.ADDR;

SELECT ADDR, PID, SPID, PROGRAM
FROM   V$PROCESS
ORDER BY PROGRAM;


-- 14
SELECT COUNT(*) AS DBW_COUNT
FROM   V$BGPROCESS
WHERE  NAME LIKE 'DBW%';


-- 15
SELECT NAME, NETWORK_NAME
FROM   V$SERVICES
ORDER BY NAME;


-- 16
SELECT NAME, VALUE
FROM   V$PARAMETER
WHERE  NAME LIKE 'dispatcher%' OR NAME LIKE 'shared_server%' 
OR NAME LIKE 'max_shared_servers' OR NAME LIKE 'distribution%';


-- 17
-- docker exec -it oracle-xe bash
-- lsnrctl status


--18 
-- cat /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora


-- 19
-- lsnrctl


-- 20
-- lsnrctl services

SELECT NAME, NETWORK_NAME, CON_ID
FROM   V$SERVICES
ORDER BY NAME;

