ALTER SESSION SET CONTAINER = XEPDB1;

--1. Разработайте локальную процедуру
--GET_TEACHERS (PCODE TEACHER.PULPIT%TYPE)
--Процедура должна выводить список преподавателей из таблицы TEACHER (в
--стандартный серверный вывод), работающих на кафедре заданной кодом в параметре.
--Разработайте анонимный блок и продемонстрируйте выполнение процедуры.

SELECT * FROM TEACHER;

DECLARE
    PROCEDURE GET_TEACHERS(PCODE TEACHER.PULPIT%TYPE)
    IS
        CURSOR PULPIT_TEACHERS IS
        SELECT * FROM TEACHER
        WHERE PULPIT = PCODE;
        V_TEACHER TEACHER%ROWTYPE;
    BEGIN
        FOR V_TEACHER IN PULPIT_TEACHERS 
        LOOP
            DBMS_OUTPUT.PUT_LINE(V_TEACHER.TEACHER || ' ' || V_TEACHER.TEACHER_NAME || ' ' || V_TEACHER.PULPIT);
        END LOOP;
    END;
BEGIN
    GET_TEACHERS('ИСиТ');
END;


--2-3. Разработайте локальную функцию
--GET_NUM_TEACHERS (PCODE TEACHER.PULPIT%TYPE)
--RETURN NUMBER
--Функция должна выводить количество преподавателей из таблицы TEACHER,
--работающих на кафедре заданной кодом в параметре. Разработайте анонимный блок и
--продемонстрируйте выполнение процедуры.
DECLARE
    FUNCTION GET_NUM_TEACHERS(PCODE TEACHER.PULPIT%TYPE)
    RETURN NUMBER
    IS
    RESULT_NUM NUMBER;
    BEGIN
        SELECT COUNT(*) INTO RESULT_NUM FROM TEACHER WHERE PULPIT = PCODE;
        RETURN RESULT_NUM;
    END;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Количество преподавателей на кафедре ИСиТ:' || GET_NUM_TEACHERS('ИСиТ'));
END;

--4. Разработайте процедуры:
--GET_TEACHERS (FCODE FACULTY.FACULTY%TYPE)
--Процедура должна выводить список преподавателей из таблицы TEACHER (в
--стандартный серверный вывод), работающих на факультете, заданным кодом в параметре.
--Разработайте анонимный блок и продемонстрируйте выполнение процедуры.
--GET_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE)
--Процедура должна выводить список дисциплин из таблицы SUBJECT, закрепленных за
--кафедрой, заданной кодом кафедры в параметре. Разработайте анонимный блок и
--продемонстрируйте выполнение процедуры.

SELECT * FROM FACULTY;

CREATE OR REPLACE PROCEDURE GET_TEACHERS_BY_FACULTY(FCODE FACULTY.FACULTY%TYPE)
    IS
    CURSOR TEACHERS_BY_FACULTY IS
    SELECT T.TEACHER_NAME, T.PULPIT FROM TEACHER T 
    JOIN PULPIT P ON T.PULPIT = P.PULPIT
    WHERE P.FACULTY = FCODE;
    
    V_TEACHER_NAME TEACHER.TEACHER_NAME%TYPE;
    V_PULPIT TEACHER.PULPIT%TYPE;
BEGIN
    
    OPEN TEACHERS_BY_FACULTY;
    LOOP
        FETCH TEACHERS_BY_FACULTY INTO V_TEACHER_NAME, V_PULPIT;
        DBMS_OUTPUT.PUT_LINE(V_PULPIT || ' ' || V_TEACHER_NAME);
        EXIT WHEN TEACHERS_BY_FACULTY%NOTFOUND;
    END LOOP;
    CLOSE TEACHERS_BY_FACULTY;
END;
    
BEGIN
    GET_TEACHERS_BY_FACULTY('ИДиП');
END;

DROP PROCEDURE GET_TEACHERS_BY_FACULTY;

SELECT * FROM SUBJECT;

CREATE OR REPLACE PROCEDURE GET_SUBJECTS(PCODE SUBJECT.PULPIT%TYPE)
    IS
    CURSOR SUBJECTS_BY_PULPIT IS
    SELECT * FROM SUBJECT WHERE PULPIT = PCODE;
    
    V_SUBJECT SUBJECT%ROWTYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Дисциплины кафедры ' || PCODE);
    FOR V_SUBJECT IN SUBJECTS_BY_PULPIT
    LOOP
        DBMS_OUTPUT.PUT_LINE(V_SUBJECT.SUBJECT || ' ' || V_SUBJECT.PULPIT);
    END LOOP;
END GET_SUBJECTS;

BEGIN
    GET_SUBJECTS('ПОиСОИ');
END;

DROP PROCEDURE GET_SUBJECTS;

--5. Разработайте локальную функцию
--GET_NUM_TEACHERS (FCODE FACULTY.FACULTY%TYPE)
--RETURN NUMBER
--Функция должна выводить количество преподавателей из таблицы TEACHER,
--работающих на факультете, заданным кодом в параметре. Разработайте анонимный блок и
--продемонстрируйте выполнение процедуры.
--GET_NUM_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER
--Функция должна выводить количество дисциплин из таблицы SUBJECT, закрепленных за
--кафедрой, заданной кодом кафедры параметре. Разработайте анонимный блок и
--продемонстрируйте выполнение процедуры.


DECLARE 
    FUNCTION GET_NUM_TEACHERS_BY_FACULTY (FCODE FACULTY.FACULTY%TYPE)
    RETURN NUMBER
    IS
    RESULT_NUM NUMBER;
    BEGIN
        SELECT COUNT(TEACHER) INTO RESULT_NUM FROM TEACHER
        WHERE TEACHER.PULPIT IN (SELECT PULPIT FROM PULPIT WHERE FACULTY=FCODE);
        RETURN RESULT_NUM;
    END;
BEGIN
    DBMS_OUTPUT.PUT_LINE(GET_NUM_TEACHERS_BY_FACULTY('ИДиП'));
END;

DECLARE 
    FUNCTION GET_NUM_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER
    IS
    RESULT_NUM NUMBER;
    BEGIN
        SELECT COUNT(SUBJECT) INTO RESULT_NUM FROM SUBJECT WHERE PULPIT=PCODE;
        RETURN RESULT_NUM;
    END;
BEGIN
    DBMS_OUTPUT.PUT_LINE(GET_NUM_SUBJECTS('ИСиТ'));
END;

--6. Разработайте пакет TEACHERS, содержащий процедуры и функции:
--GET_TEACHERS (FCODE FACULTY.FACULTY%TYPE)
--GET_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE)
--GET_NUM_TEACHERS (FCODE FACULTY.FACULTY%TYPE) RETURN NUMBER
--GET_NUM_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER

CREATE OR REPLACE PACKAGE TEACHERS AS
    FCODE FACULTY.FACULTY%TYPE;
    PCODE SUBJECT.PULPIT%TYPE;
    PROCEDURE P_GET_TEACHERS(FCODE FACULTY.FACULTY%TYPE);
    PROCEDURE P_GET_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE);
    FUNCTION P_GET_NUM_TEACHERS(FCODE FACULTY.FACULTY%TYPE) RETURN NUMBER;
    FUNCTION P_GET_NUM_SUBJECTS(PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER;
END TEACHERS;

CREATE OR REPLACE PACKAGE BODY TEACHERS
IS
    PROCEDURE P_GET_TEACHERS(FCODE FACULTY.FACULTY%TYPE)
    IS
        CURSOR TEACHERS_BY_FACULTY IS
        SELECT T.TEACHER_NAME, T.PULPIT FROM TEACHER T 
        JOIN PULPIT P ON T.PULPIT = P.PULPIT
        WHERE P.FACULTY = FCODE;
        
        V_TEACHER_NAME TEACHER.TEACHER_NAME%TYPE;
        V_PULPIT TEACHER.PULPIT%TYPE;
    BEGIN
        OPEN TEACHERS_BY_FACULTY;
        LOOP
            FETCH TEACHERS_BY_FACULTY INTO V_TEACHER_NAME, V_PULPIT;
            DBMS_OUTPUT.PUT_LINE(V_PULPIT || ' ' || V_TEACHER_NAME);
            EXIT WHEN TEACHERS_BY_FACULTY%NOTFOUND;
        END LOOP;
        CLOSE TEACHERS_BY_FACULTY;
    END P_GET_TEACHERS;

    PROCEDURE P_GET_SUBJECTS(PCODE SUBJECT.PULPIT%TYPE)
    IS
        CURSOR SUBJECTS_BY_PULPIT IS
        SELECT * FROM SUBJECT WHERE PULPIT = PCODE;
        
        V_SUBJECT SUBJECT%ROWTYPE;
    BEGIN
        DBMS_OUTPUT.PUT_LINE('Дисциплины кафедры ' || PCODE);
        FOR V_SUBJECT IN SUBJECTS_BY_PULPIT
        LOOP
            DBMS_OUTPUT.PUT_LINE(V_SUBJECT.SUBJECT || ' ' || V_SUBJECT.PULPIT);
        END LOOP;
    END P_GET_SUBJECTS;
    
    FUNCTION P_GET_NUM_TEACHERS (FCODE FACULTY.FACULTY%TYPE)
    RETURN NUMBER
    IS
        RESULT_NUM NUMBER;
    BEGIN
        SELECT COUNT(TEACHER) INTO RESULT_NUM FROM TEACHER
        WHERE TEACHER.PULPIT IN (SELECT PULPIT FROM PULPIT WHERE FACULTY=FCODE);
        RETURN RESULT_NUM;
    END P_GET_NUM_TEACHERS;
    
    FUNCTION P_GET_NUM_SUBJECTS (PCODE SUBJECT.PULPIT%TYPE) RETURN NUMBER
    IS
        RESULT_NUM NUMBER;
    BEGIN
        SELECT COUNT(SUBJECT) INTO RESULT_NUM FROM SUBJECT WHERE PULPIT=PCODE;
        RETURN RESULT_NUM;
        END P_GET_NUM_SUBJECTS;
END TEACHERS;

BEGIN 
    DBMS_OUTPUT.PUT_LINE('Пакет TEACHERS');
    TEACHERS.P_GET_TEACHERS('ИДиП');
    TEACHERS.P_GET_SUBJECTS('ИСиТ');
    DBMS_OUTPUT.PUT_LINE('Количество преподавателей на факультете: ' || TEACHERS.P_GET_NUM_TEACHERS('ИДиП'));
    DBMS_OUTPUT.PUT_LINE('Количество дисциплин на кафедре: ' || TEACHERS.P_GET_NUM_SUBJECTS('ИСиТ'));
END;