-- Вариант 2

-- 1
SELECT * FROM CDB_USERS 
WHERE COMMON = 'YES';

-- 2
SELECT * FROM DBA_PROFILES;

-- 3
SELECT * FROM USER_OBJECTS;

-- 4
SELECT TABLE_NAME, ROUND(BLOCKS * (SELECT VALUE FROM V$PARAMETER WHERE NAME = 'db_block_size'), 2)
FROM USER_TABLES
WHERE TABLE_NAME = 'USER$';

-- 5
SELECT NAME FROM V$ARCHIVED_LOG;

-- 6
SELECT * FROM V$PARAMETER
WHERE NAME = 'control_files';

-- 7
SELECT VALUE FROM V$PARAMETER
WHERE NAME = 'spfile';

-- 8
SELECT LOG_MODE FROM V$DATABASE;

-- 9
SELECT GRANULE_SIZE FROM V$SGA_DYNAMIC_COMPONENTS
WHERE ROWNUM = 1;

SHOW PARAMETER GRANULE_SIZE;

-- 10
SELECT * FROM V$PROCESS;
